# Generated by Django 2.2 on 2022-11-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectCar', '0006_rename_contact_us_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
